baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Knowledge Foundation'
email: 'write2kfoundation@gmail.com'

# Pagination
paginate: 6
paginate_path: "blog/page:num"

collections:
  courses:
    output: true
    permalink: /courses/:path/
  team:
    output: true
    permalink: /team/:path/
  testimonials:
    output: true
    permalink: /testimonials/:path/
  posts:
    output: true
    permalink: /posts/:path/

defaults:
  - scope:
      type: courses
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: null

plugins:
  - jekyll-environment-variables
  - jekyll-paginate
